-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.45,
        blur = {
            passes = 2,
            size = 1,
            vibrancy = 0.04,
        },
        inactive_opacity = 0.3,
        shadow = {
            enabled = false,
        },
    },
    dwindle = {
        smart_split = true,
    },
    general = {
        border_size = 3,
    },
})

-- Bezier curves
hl.curve("ease", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })
hl.curve("specialWorkSwitch", { type = "bezier", points = { {0.05, 0.7}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 5.0,
    bezier = "ease",
    style = "gnomed",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 5.0,
    bezier = "specialWorkSwitch",
    style = "popin",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5.0,
    bezier = "specialWorkSwitch",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.0,
    bezier = "specialWorkSwitch",
    style = "slidefade",
})
