# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#0e0e0e

# Main text color
theme[main_fg]=#e6e6e6

# Title color for boxes
theme[title]=#e6e6e6

# Highlight color for keyboard shortcuts
theme[hi_fg]=#c6c6c6

# Background color of selected item in processes box
theme[selected_bg]=#191919

# Foreground color of selected item in processes box
theme[selected_fg]=#c6c6c6

# Color of inactive/disabled text
theme[inactive_fg]=#757575

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#e8e4e7

# Background color of the percentage meters
theme[meter_bg]=#757575

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#e8e4e7

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#b7bfe3
theme[mem_box]=#d9e1e9
theme[net_box]=#bebbd5
theme[proc_box]=#acbde3

# Box divider line and small boxes line color
theme[div_line]=#484848

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#d9e1e9
theme[temp_mid]=#ecf2f0
theme[temp_end]=#afafe2

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#dbe0e8
theme[cpu_mid]=#b7c8e4
theme[cpu_end]=#c5cce4

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#b7bfe3
theme[free_mid]=#c5cce4
theme[free_end]=#acbde3

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#b7c8e4
theme[cached_mid]=#acbde3
theme[cached_end]=#c5cce4

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#d8c8e2
theme[available_mid]=#bebbd5
theme[available_end]=#afafe2

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#d9e1e9
theme[used_mid]=#dbe0e8
theme[used_end]=#d6dbe7

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#d8c8e2
theme[download_mid]=#bebbd5
theme[download_end]=#afafe2

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#d9e1e9
theme[upload_mid]=#dbe0e8
theme[upload_end]=#d6dbe7

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#b7c8e4
theme[process_mid]=#c5cce4
theme[process_end]=#b7bfe3
